server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          #开启从注册中心创建动态路由的功能，利用微服务名进行路由
          enabled: true
      routes:
        #路由id，要求唯一
        - id:    YHZX
          #匹配后提供服务的路由地址
          uri: lb://YHZX
          predicates:
            #断言，路径相匹配的进行路由
            - Path=/yhzx/**
          filters:
            #去掉URL路径中的部分前缀(/api)
            #- StripPrefix=1

eureka:
  instance:
    #以ip形式注册
    prefer-ip-address: true
    #客户端向服务端发送心跳的间隔
    lease-renewal-interval-in-seconds: 5
    #实例超时时间
    lease-expiration-duration-in-seconds: 10
    #注册到eureka上的唯一实例ID
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #实例元数据，供其他实例使用
    metadata-map:
      configPath: ${server.servlet.context-path:}
      management.context-path: ${server.servlet.context-path:}/actuator
      version: 1.0
    #实例主页绝对url
    #home-page-url-path: ${server.servlet.context-path:}
    #实例健康检查相对url
    #health-check-url-path: ${server.servlet.context-path:}/actuator/health
    #实例状态页绝对url
    #status-page-url-path: ${server.servlet.context-path:}/swagger-ui.html
  client:
    #从eureka-server获取注册表
    fetch-registry: true
    #注册到eureka
    register-with-eureka: true
    service-url:
      defauleZone: http://localhost:8761/eureka
    #定时从eureka serve拉取服务注册信息的间隔时间
    registry-fetch-interval-seconds: 5


resource:
  filter:
    config:
      excludeUrls:
        - /api/yhzx/user/gertUserInfo