server:
  port: 8761

spring:
  application:
    name: eureka
  redis:
    database: 0
    timeout: 3000 #超时时间3秒
    password: 123456789
      #################################哨兵模式
      #host: 192.168.100.129
      #port: 6379
      #password: 123456789
      #sentinel:
      #主服务器所在集群名称
    #master: mymaster
    #nodes: 192.168.100.129:26379,192.168.100.129:26380,192.168.100.129:26381
    cluster:
      nodes:
        - 192.168.100.129:8001
        - 192.168.100.129:8004
        - 192.168.100.130:8005
        - 192.168.100.130:8002
        - 192.168.100.131:8003
        - 192.168.100.131:8006
    lettuce:
      pool:
        #连接池最大连接数(使用负数表示没有限制) 默认8
        max-active: 8
        #连接池最大阻塞等待时间(使用负数表示没有限制)
        max-wait: 1000
        #连接池中的最大空闲连接默认8
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0
  cache:
    type: redis

eureka:
  client:
    #是否向注册服务注册自己
    register-with-eureka: false
    #是否检索服务
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  server:
    #自我保护机制
    enable-self-preservation: false